
* Totui

Totui is a terminal todo list manager. The name /Totui/ is from the words "TOdo" and "TUI" (terminal user interface).

** Building 

You can

1. Clone the repo: =git clone https://github.com/yaaama/totui=
2. Go into the cloned folder: =cd totui=
3. Make the file =make=
4. Run the program: =./totui=

* Usage guide

The keybindings are simple. They are inspired by *vim* keys.

Move up: <kbd>k</kbd>
Move down: <kbd>j</kbd>
Insert new todo: <kbd>a</kbd>
Delete the currently selected todo item: <kbd>d</kbd>
Quit the program: <kbd>q</kbd>
Toggle the todo status: <kbd>SPACE</kbd>



* Things to do (no pun intended)

** Core functionality

- [x] Can traverse through todo items displayed on the screen.
- [x] User can add a new todo item.
- [x] Todo items can be deleted.
- [x] Toggle todo items
- [ ] User can specify the default file they want to use.
- [ ] Resize application as the window is resized.
- [ ] Echo bar on the bottom (displays information about user actions and program processes).
- [ ] Help bar on the top (displays q to quit, etc).
- [ ] Warnings for when the user may insert too long of a todo.


** Aesthetics
- [ ] A line containing something longer than the terminal width should be truncated on the screen.
  - Program should calculate how many lines the new item is occupying, and then move the cursor so that it is below the new item.
- [ ] Lines that overflow the buffer should be rejected
- [x] Colour lines based on status.
- [ ] 

** Perhaps in the future

- [ ] A split plane where the user can add more information about each todo (not limited by character counts).
- [ ] Configuration file where the user can specify the file to store the todo items in.

